[package]
name = "cfg-exif"
description = "Conditional compilation in expressions"
version = "0.3.0"
edition = "2021"
license-file = "./UNLICENSE"

[workspace.lints.rust]
missing_docs = "deny"
warnings = "deny"
